### ISSUE TITLE
the done parser fails with comment containing carriage return

### ISSUE THREAD

**Issue by kfule** [MithrilJS/ospec#14]
the done parser doesn't care about comments with carriage return

if we use git with  "checkout Windows-style, commit Unix-style line endings" setting on Windows, the test "the done parser > tolerates comments" fails

maybe same issue https://github.com/MithrilJS/mithril.js/issues/2351

**Comment by pygy** [comment]
Good catch, I'm on it.

**Comment by pygy** [comment]
Could you try the git master?

**Comment by kfule** [comment]
@pygy 
I ran master's tests on Windows with "checkout Windows-style, commit Unix-style line endings" 
 git setting.
Looks good, thank you!

**Comment by pygy** [comment]
#15 and #16 address this. Thanks again for the report.
