### ISSUE TITLE
Remove devDependencies before publish to NPM

### ISSUE THREAD

**Issue by futurist** [MithrilJS/ospec#29]
The devDependencies make no sense in  npm package, just make the installation longer and heavier.

```json
"devDependencies": {
        "compose-regexp": "0.4.0",
        "eslint": "^6.8.0",
        "ospec": "4.0.1"
}
```
If the sales point is light weight, above should be get rid off before publish.

**Comment by isiahmeadows** [comment]
Those won't be installed when you `npm install ospec`. npm's smart enough not to instal those as they're dev-only.

Don't see the need to statically compile that out when publishing.
