### ISSUE TITLE
Support running Ospec against TypeScript files

### ISSUE THREAD

**Issue by chanks** [MithrilJS/ospec#4]
As discussed in gitter: https://gitter.im/mithriljs/mithril.js?at=5d6b2250418f705d876fc8d6

@isiahmeadows felt this would be low-effort to support.

**Is this something you're interested in implementing yourself?**

No, sorry, not quite my expertise :grimacing:

**Comment by pygy** [comment]
What about [`--require ts-node/register`](https://github.com/TypeStrong/ts-node) (soon to be `--preload ts-node/register`)?

**Comment by pygy** [comment]
Closing this as it seems to work
