### ISSUE TITLE
Failed assertion reporting does unnecessary string substitution

### ISSUE THREAD

**Issue by LeXofLeviafan** [MithrilJS/ospec#57]
Suppose I have a test like this:

```js
o('%foo').equals('%ioo')("%doo")
```

When evaluated, I'd expect for this expression to produce the following output:
```
%doo

'%foo'
  should equal
'%ioo'
```

What I'm getting instead is this:
```
0oo

'NaNoo'
  should equal
'NaNoo'
```

Now I'm guessing this has to do with [format placeholders](https://en.wikipedia.org/wiki/Printf_format_string), but I'm fairly sure that any such substitution should only be performed _once_ (so that it does not affect the inserted text).

_Edit:_ checked `o.spec("%foo", () => o("%foo", () => {/* … */}))` – these strings are also affected.

**Comment by pygy** [comment]
@LeXofLeviafan Thanks for the report, this is indeed a bug and I suspect your analysis is correct. I'll look into it.

**Comment by pygy** [comment]
This will be published soon, probably this evening.
