### ISSUE TITLE
ospec requires a polyfill, but this appears undocumented and doesn't exist in the test HTML file

### ISSUE THREAD

**Issue by isiahmeadows** [MithrilJS/ospec#6]
Somehow, I missed this entirely when running the tests.

**Comment by pygy** [comment]
Does ospec need it, or only the test suite? I would have guessed only the latter...

**Comment by isiahmeadows** [comment]
Only the test suite - I misinterpreted [this](https://github.com/MithrilJS/ospec/pull/2#discussion_r338358157)

**Comment by isiahmeadows** [comment]
I've closed it since the immediate issue was fixed in #2.
