### ISSUE TITLE
Travis build status shield/badge 404ing

### ISSUE THREAD

**Issue by codingthat** [MithrilJS/ospec#72]
![image](https://github.com/user-attachments/assets/2da8d630-d0af-4c7e-9b2c-2898e03e3c7c)

I noticed the URL has "master" instead of "main," but changing it to "main" still 404s for me, so there may be multiple issues at play...

**Comment by dead-claudia** [comment]
Related: #70

(I'm just horribly time-strapped and haven't yet had a chance to fix it.)

**Comment by dead-claudia** [comment]
And fixed, along with a new ospec version to get rid of a deprecation warning. 🙂
