### ISSUE TITLE
Travis doesn't build against Node.js v20 or v22

### ISSUE THREAD

**Issue by codingthat** [MithrilJS/ospec#73]
Noticed on the popup from https://github.com/MithrilJS/ospec/commit/dbce1afbb0ad0b18a3f07a9e06a3856bff2cc90c :
![image](https://github.com/user-attachments/assets/73d19793-4ee0-448b-a790-97982487a2d6)

Both versions would be good since v20 is in active LTS and v22 is current.

**Comment by dead-claudia** [comment]
Travis doesn't build at all. Plans to resolve this are in #70

**Comment by dead-claudia** [comment]
And fixed, along with a new ospec version to get rid of a deprecation warning. 🙂
